name: Auto Merge Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Run every 3 days at 00:00 UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/fuergaosi233/claude-code-proxy.git
          git remote -v
          
      - name: Fetch Upstream
        run: |
          git fetch upstream
          
      - name: Merge Upstream
        run: |
          git merge upstream/main --no-edit
          
      - name: Push Changes
        run: |
          git push origin main 